app/email_login_confirmation/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, request 
from app import db
# used because I want to render login route
from app.auth.forms import LoginForm
from app.email_login_confirmation.forms import TokenForm 
from app.models import User
from flask_mail import Message
# from __init__.py
from app import mail
from sqlalchemy import delete

from app.email_login_confirmation.functions import create_token_db, count_attempts_token_tried, create_time_token_db \
, check_expired_token, wait_max_thirty_min_for_new_token, reset_attempts_token_tried_to_0
from datetime import datetime



email_login_confirmation = Blueprint('email_login_confirmation', __name__, template_folder='templates')
'''
Summary:

Send the email and a fill out the token form. 
Now you can login because you clicked on the confirmation_email and it is true in the db. 
'''

def send_registration_token_email(user_db): # should I move this and rename it ? Probably
    '''
    send email to your email account with a token. 
    This function is in the /registration_verification_code/<username_db> + the previous route
    '''
    create_token_db(user_db)
    count_attempts_token_tried(user_db)
    create_time_token_db(user_db, now=datetime.now())

    subject='Here is the token for the email'
    sender=("do_not_reply@example.com")
    recipients = [user_db.email]

    email_token_db = user_db.email_token 

    subject=subject
    sender=sender
    recipients = recipients
    msg = Message(subject, sender=sender, recipients=recipients)
  
    msg.html = render_template('_send_confirmation_token_email.html', username_db=user_db.username, email_token_db=email_token_db)
    mail.send(msg)


# todo better wording
# is route_token needed in the route.
# 
@email_login_confirmation.route('/registration_verification_code/<username_db>', methods = ['GET', 'POST']) 
def registration_verification_code(username_db):      
    '''
    functions checks the verification token then adds the confirmation_email to True so you can login
    '''
    user_db = db.one_or_404(db.select(User).filter_by(username=username_db))  
    # registration_confirmation_email is True + prevents you from registering twice.  
    if user_db.registration_confirmation_email == True:        
        form = LoginForm()
        flash('You have already registered. Please Login.')
        return render_template('login.html', title='login', form=form, error=None)
    
     
    # This only runs before user_db.email_token table exists for a user
    if user_db.email_token is None: # not working!!
        flash('A token has been sent to your email. Please follow the instructions in your email.' )
        # send email. 
        # The email gives you a token for the form + will redirect to you 'confirmation.registration_verification_code/route_token'        
        # user_db.registration_confirmation_email is currently False:
        send_registration_token_email(user_db)
        
    form = TokenForm()  
    if form.validate_on_submit():
        email_token_db = user_db.email_token 
        token_form = form.email_token.data

        # check if the email token from the db and the token_form match
        if email_token_db != token_form: # need a more secure way to compare
            # I am only deleting the token because I want the token to be able to be expired.
            db.session.execute(delete(User).where(User.email_token == user_db.email_token))
            db.session.execute(delete(User).where(User.time_token_expired == user_db.time_token_expired))
            flash('Your token did not match the one sent to your email.') 
            flash('Please request a new token.')
            return render_template('registration_verification_code.html', title='registration login code', form=form, user_db=user_db)
        
        check_expired_token(user_db, now=datetime.now())
        # is this secure
        if wait_max_thirty_min_for_new_token(user_db=user_db, now=datetime.now()) == 'will redirect to email_login_confirmation route':
            return redirect(url_for('email_login_confirmation.registration_verification_code', username_db=user_db.username))
        # is this secure        
        elif reset_attempts_token_tried_to_0(user_db, now=datetime.now())== 'going to redirect to login':
            return redirect(url_for('auth.login'))
        else:
            # if the token matches the form and nothing else is wrong the code below executes
            user_db.registration_confirmation_email = True
            user_db.email_token = None
            user_db.time_token_expired = None
            user_db.attempts_token_tried = 0
            db.session.commit()
            # user_db.registration_confirmation_email is now True
            flash('You can now login.')
            return redirect(url_for('auth.login'))
    
    return render_template('registration_verification_code.html', title='registration login code', form=form, user_db=user_db)

# is route_token needed in the route?   
@email_login_confirmation.route('/resend_login_confirmation_token/<username_db>', methods = ['GET', 'POST']) 
def resend_login_confirmation_token(username_db):    
 
    user_db = db.one_or_404(db.select(User).filter_by(username=username_db))  
    # registration_confirmation_email is True + prevents you from registering twice.  
    if user_db.registration_confirmation_email == True:        
        form = LoginForm()
        flash('You have already registered. Please Login.')
        return render_template('login.html', title='login', form=form, error=None)
    
    check_expired_token(user_db, now=datetime.now())
    # is this secure
    if wait_max_thirty_min_for_new_token(user_db=user_db, now=datetime.now()) == 'will redirect to email_login_confirmation route': 
        return redirect(url_for('email_login_confirmation.registration_verification_code', username_db=user_db.username))
    # is this secure        
    elif reset_attempts_token_tried_to_0(user_db, now=datetime.now())  == 'going to redirect to login':
        return redirect(url_for('auth.login'))
    else:    
        flash('A token has been sent to your email. Please follow the instructions in your email.' )
        send_registration_token_email(user_db) 
        return redirect(url_for('email_login_confirmation.registration_verification_code', username_db=user_db.username))

app/postinfo/routes.py
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app import db
from app.models import Posts, User
from app.postinfo.forms import Emptyform, Postform

''' 
# todo turn into a database why is there no post number like 1st post ever posted in general etc?
posts = {   
    "username": "author",
    "author": "Bobby Bobson",
    "Title": "Hello World",
    "Content": "This is a post content 1",
    "date_posted": "March 17 2021" 
}
'''
postinfo = Blueprint('postinfo', __name__, template_folder='templates')

@postinfo.route("/post/new", methods = ['POST', 'GET'])
@login_required
# I need to link to the name of the function in the html. Ex new_post 
def new_post(): 
    form = Postform()
    if form.validate_on_submit():
        title_form = form.title.data
        content_form = form.content.data
        date_posted_form = datetime.now()
        # user.id is used in the FK in the Post database. You need to manually add FK's.   
        user_db = db.session.execute(db.select(User).filter_by(username=current_user.username)).scalar_one_or_none()
        user_db_id = user_db.id
        posts = Posts(title=title_form, content=content_form, date_posted=date_posted_form, fk_user_id=user_db_id )  
        db.session.add(posts)  
        db.session.commit()          
        flash('You have posted successfully') 
        # redirect to the post after complete because you want to see the posted post. 
        return redirect(url_for('main.home'))
    return render_template('new_post.html',title='new post', form=form)



# gives you the ability to click on a post and view it 
# get the unique post from the post id
@postinfo.route("/post/<int:post_id_db>", methods = ['POST', 'GET'])
@login_required
def post(post_id_db):
    post_db = db.get_or_404(Posts, post_id_db)
    post_id_db = post_db.id

    user_db = db.one_or_404(db.select(User).filter_by(username=current_user.username))
    form = Emptyform()    
    # Do I need to pass on post_id 
    return render_template('post.html', title='post', form=form,post_db=post_db, post_id_db=post_id_db, user_db=user_db)





# The reason you have post_id is because you only want to edit 1 post at a time. 
# If you leave out post_id you would edit every posts. 
@postinfo.route("/post/edit/<int:post_id_db>", methods = ['POST', 'GET'])
# edit/update posts
@login_required
def edit_post(post_id_db): 
    # get request
    post_db = db.one_or_404(db.select(Posts).filter_by(id=post_id_db))  
    form = Postform()
    if form.validate_on_submit():
        # delete the current columns in db
        delete_post = post_db
         
        db.session.delete(delete_post)  
        db.session.commit()
        # add/edit the current forms in the db
        title_form = form.title.data
        content_form = form.content.data 
        posts = Posts(title=title_form, content=content_form ,fk_user_id=current_user.id)
        db.session.add(posts)  
        db.session.commit()
        flash('You have edited your post successfully')
        return redirect(url_for('main.home'))
      # put this below the if statement so for ex "form.title.data" doesn't interfere with above ex "form.title.data
    elif request.method == 'GET':        
       
        post_title_db = post_db.title
        post_content_db = post_db.content
        # the code below renders a form with text already in the form
        form.title.data =  post_title_db 
        form.content.data = post_content_db
        return render_template('edit_post.html', title='edit post', form=form) 






# Can I go ("/post/<int:post_id>/delete") instead of below? No
@postinfo.route("/post/delete/<int:post_id_db>", methods = ['POST'])
@login_required
def delete_post(post_id_db): 
    if request.method == 'POST':       
        post_db = db.one_or_404(db.select(Posts).filter_by(id=post_id_db))  
        delete_post = post_db
        db.session.delete(delete_post)
        db.session.commit()
        flash('You have deleted your post')
        return redirect(url_for('main.home'))
    

app/templates/_render_form.html
{% macro render_form(field) %}
    {% if field == searchform %}
        {{field.name}} 
    {% else %}
        <label for="{{field.name}}" class="pb-2 col-form-label"> {{field.label.text}} </label>
    {% endif %}

            <!-- ask if this code is safe? why do I need ** and not *? -->
            {{ field(class='form-control', **kwargs)|safe }}
            {% for error in field.errors %}
                    <li style="color:red;"> {{error}} </li> 
            {% endfor %}
{% endmacro %}

app/templates/_send_password_reset_token_email.html
<!-- For password reset--> 
<!doctype html>
<html>
    <body>
        <html>
            <body>
                <p>
                    Here is the password token code. Please type  <h1> <b> "{{email_token_db}}" </b> </h1> in the form. 
                    If you did not make this request then simply ignore this email and no changes will be made. 
                    To fill out the token so you can reset your password, visit the following link: 
                    <!-- for security purposes you want to be able to see the full link?-->
                    <a href="{{url_for('email_password_reset.verify_email_token', username_db=username_db, token_db=token_db, _external=True)}}" target="_blank">
                        url_for('email_password_reset.verify_email_token', username_db=username_db, token_db=token_db, _external=True)
                    </a> 
                </p>
            </body>
        </html>
    </body>
</html>   








<!-- make sure _send_password_reset_email.html -->

app/templates/about.html
{%extends "layout.html"%}
    {% block title %} {{title}} {% endblock title %} 
    {%block content%}
    <p class="d-flex justify-content-center">
        <br>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus voluptates vero dolorum, minima </br>
        <br>
            dolores consequatur architecto earum impedit, eum distinctio nobis. 
        </br>
        <br>
            Praesentium provident et culpa voluptate, soluta enim necessitatibus facere!
        </br>
    </p>
    {%endblock content%}

app/templates/cancel.html
{% extends "layout.html" %}


{% block content %} 
  <title> Stripe and Flask Demo </title>
 
  <h1> Stripe and Flask Demo </h1>
  <p> The order was cancelled. </p>
  <p> <a href="/"> Home </a></p>
{% endblock content %}


 

app/templates/home.html
{% extends "layout.html" %}
 <!-- title is flashblog -->
{% block title %} {{title}} {% endblock title %} 
{% block post_info %}   

    {% if posts_db %} 

        {% for post_db in posts_db %}
            <h2> <a href="{{ url_for ('postinfo.post', post_id_db =post_db.id) }}"> {{post_db.title}} </a> </h2>
        {% endfor %}
    {% endif %}
    


    
{% endblock post_info %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head> 
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">      
    <!-- render flask wtf forms with bootstrap -->
    {% from "_render_form.html" import render_form %}
    <!-- CSS -->
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    
    {% if title %}
    <title> flashblog {{+ title}} </title>
    <!-- The title will say home -->
    {% else %} 
           {{ 'home' }}
    {% endif %}

</head>
<body>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


 
    <!-- include the navbar which contains the searchform -->
    {% include 'navbar.html' %}
    


    
    <!-- search results-->
    {% block searching_results %}
    {% endblock searching_results %}

    {% block content %} 
    {% endblock content %}
  




     <!-- From home. Prints userpost information -->
    {% block post_info %}    
    {% endblock post_info %}

    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class=flashes>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
   
    {% endwith %}
    {% block body %}{% endblock %}
    

</body>
</html>



  

app/templates/new_post.html
{% extends "layout.html" %}
<!-- get the error message from wtf forms -->
{% from "_formhelpers.html" import render_field %}
<!-- title is "edit_post or new_post" -->
{% block title %}  {{title}}  {% endblock title %} 

<!-- should I use block content or an different name?-->
{% block content %}  
        <!-- Once you get the error message from ( "_formhelpers.html" import render_field) , you use novalidate to 
        get the error message from wtf forms and makes it show up on the screen. %} -->
        <form validate action="" id="new_post" method="POST">  
                <!-- Make the secret key work -->
                {{ form.csrf_token }}
                {{ render_field(form.title) }}
                {{ render_field(form.content) }}
                <input type="submit" value="Submit">  
        </form>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='content') }}
      

        <!--make flash message work-->
        {%with messages = get_flashed_messages()%}
        {%if messages %}
                <ul class=flashes>
                {%for message in messages%}
                        <p1>  {{message}} </p1>
                {% endfor %}
                        </ul>
        {% endif %}
        {% endwith %}
        
{% endblock content %}

app/templates/post.html
  
{% extends "layout.html" %}
 
<!-- title is post or edit_post -->
{% block title %}  {{title}}  {% endblock title %} 

{% block content %}
        
        <!-- When the if statement executes the edit and delete button appears. If clicked you are taken to edit_post route or delete from new_post -->       
        <!-- Only the original poster can edit there post. -->
        {% if current_user.is_authenticated and post_db.fk_user_id == user_db.id %} 
                <!--  post_id = post/nth --> 
                <h2> <a href="{{ url_for('postinfo.edit_post', post_id_db=post_id_db)  }}"> <button> edit</button> </a> </h2>    
                
                <form method="POST" id="delete_post" action="{{ url_for('postinfo.delete_post', post_id_db=post_id_db) }}">
                        {{ form.csrf_token }}     
                        <input type="submit" value="delete">
                </form>

                
        {% endif %} 
                <!-- /post route -->                    
                <!-- click on profile -->
                <h2> <a href="{{ url_for ('main.profile', username=user_db.username) }}">  {{ (user_db.username) }} </a> </h2>                                                 
                {{ (post_db.title) }}
                {{ (post_db.content) }} 
                {{ (post_db.date_posted) }}                     




        <!--make flash message work-->
        {%with messages = get_flashed_messages()%}
        {%if messages %}
                <ul class=flashes>
                {%for message in messages%}
                        <p1>  {{message}} </p1>
                {% endfor %}
                </ul>
        {% endif %}
        {% endwith %}


{% endblock content %}

app/templates/registration_verification_code.html
{% extends "layout.html" %}
<!-- render flask wtf forms with bootstrap -->
{% from "_render_form.html" import render_form %}

{% block title %} {{title}} {% endblock title %} 
{%block content%}
    <div class="container-fluid"> 
        <div class="row">
            <!-- 
            novalidate makes it so the flask code does the validating
            -->
            <form action="" id="registration_verification_code" method="POST" novalidate> 
            <!-- 
            ms-auto setting the left and right margins of the element to auto
            text-center centers the elements with text
            -->
                <div class="col-lg-5 card text-white bg-dark rounded mx-auto mt-5">
                    <div class="card-body">
                        <h5 class="card-title">Please Login</h5>
                        <!-- Make the secret key work -->
                        {{ form.csrf_token }} 
                        <!--  token form function -->
                        {{ render_form(form.email_token, placeholder=form.email_token.label.text) }}
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-success btn-lg">verify token</button>
                        </div>            
                    </div>
                </div>    
            </form>
             
            {% if user_db.emal_token != None %}
                <!-- "resend token button" that redirects you to an route that resends the email with the token  -->
                <!--does this need to be a post request ?-->
                <div id="resend_token" class="d-flex justify-content-center mt-3">     
                    <a class="btn btn-primary" href="{{url_for('email_login_confirmation.resend_login_confirmation_token', username_db=user_db.username)}}" role="button">resend token</a>
                </div>  
    
                <p> If you did not recieve an token then click resend token. </p>
            {% endif %}    

        </div> <!--row div-->            
    </div> 
{%endblock content%}      

app/templates/reset_token.html
{% extends "layout.html" %}
<!-- render flask wtf forms with bootstrap -->
{% from "_render_form.html" import render_form %}


{% block title %} {{title}} {% endblock title %} 
{%block content%}
    <div class="container-fluid"> 
        <div class="row">
            <!-- 
            novalidate makes it so the flask code does the validating
            -->
            <form action="" id="reset_token" method="POST" novalidate> 
            <!-- 
            ms-auto setting the left and right margins of the element to auto
            text-center centers the elements with text
            -->
                <div class="col-lg-5 card text-white bg-dark rounded mx-auto mt-5">
                    <div class="card-body">
                        <h5 class="card-title"> add the token from your email</h5>
                        <!-- Make the secret key work -->
                        {{ form.csrf_token }} 
                        <!--  token form function -->
                        {{ render_form(form.token, placeholder=form.token.label.text) }}
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-success btn-lg">verify token</button>
                        </div>            
                    </div>
                </div>    
            </form>
            <div class="d-flex justify-content-center mt-3">
                <a href="{{url_for('email_password_reset.reset_token', username_db=username_db)}}" class="btn btn-primary" role="button">resend token</a>
            </div>
        </div> <!--row div-->            
    </div> 
{%endblock content%}      

app/templates/search.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import render_field %}

{% block title %} {{title}} {% endblock title %} 
{% block searching_results %}

 
    {{ searchform.csrf_token }} 
    {% if search_results %}

        <br> <h2> You searched for... </h2> </br>
        {% for search_result in search_results %}
            {{ search_result }}
        {% endfor %}
        
        {% for post_db in search_results %}
            <!-- create a new_form for post information called post.html and rename post.html to new_post.html? -->
            <a href="{{ url_for('postinfo.post', post_id_db = post_db.id) }}"> {{ post_db.title }} </a>
        {% endfor %}

    {% else %}    
        <h2> Your search did not find anything. Please try again. </h2>
    {% endif %}


 

{% endblock searching_results %}      

app/templates/success.html
{% extends "layout.html" %}


{% block content %} 
  <title> Stripe and Flask Demo </title>
 
  <h1> Stripe and Flask Demo </h1>
  <p> Thank you for your order! </p>
  <p> <a href="/"> Home </a></p>
{% endblock content %}

app/templates/update_profile.html
<!--upload and update profile pics-->
        {% extends "layout.html" %}
 
    <!-- title is post -->
    {% block title %}  {{title}}  {% endblock title %} 
        
    <!--should block content have a different name?  -->
    {% block content %} 
        <!-- Once you get the error message from ( "_formhelpers.html" import render_field) , you use novalidate to 
        get the error message from wtf forms and makes it show up on the screen. %} -->
        <!-- @postinfo.route("/post/edit/<int:post_id>", methods = ['POST', 'GET'] -->
        <!-- enctype= is for uploads. Used if using filefield "multipart/form-data" -->   
        <form validate action="/edit_profle" id="/edit_profle_forms"  enctype="multipart/form-data"  method="POST"> </form> 
        <!-- makes it so you can only accept certain files --> 
        <input type="file" name="upload" accept=" '.jpg', '.png' ">
            <!-- Make the secret key work for forms -->
            {{form.csrf_token}} 
            {{ form.update_password }}
            <!-- {{l}} add's the profile image upload -->
            <h1> todo delete profile button </h1> 
            <button type="update_button"> update </button> 

    {% endblock content %}

    

    <!--make flash message work-->
    {%with messages = get_flashed_messages()%}
    {%if messages %}
        <ul class=flashes>
        {%for message in messages%}
        <p1>  {{message}} </p1>
        {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}

app/templates/verify_email.html
{% extends "layout.html" %}
<!-- get the error message from wtf forms -->
{% from "_formhelpers.html" import render_field %}
<!-- render flask wtf forms with bootstrap -->
{% from "_render_form.html" import render_form %}

{% block content %}

<div class="container-fluid"> 
    <div class="row">
        <!-- 
        novalidate makes it so the flask code does the validating
        -->
        <form action="" id="verify email" method="POST" novalidate> 
        <!-- 
        ms-auto setting the left and right margins of the element to auto
        text-center centers the elements with text
        -->
            <div class="col-lg-5 card text-white bg-dark rounded mx-auto mt-5">
                <div class="card-body">
                    <h5 class="card-title">Verfiy Email</h5>
                    <!-- Make the secret key work -->
                    {{ form.csrf_token }} 
                    <!-- email form function -->
                    {{ render_form(form.email, placeholder=form.email.label.text) }}
                    <!-- button -->
                    <div class="d-flex justify-content-center mt-4">
                        <button type="submit" class="btn btn-success btn-lg">submit </button>
                    </div>
                </div>
            </div>    
        </form>
    </div> <!--row div-->            
</div> 

        <!--make flash message work-->
        {%with messages = get_flashed_messages()%}
        {%if messages %}
                <ul class=flashes>
                {%for message in messages%}
                        <p1>  {{message}} </p1>
                {% endfor %}
                </ul>
        {% endif %}
        {% endwith %}



{% endblock content %}